# These are supported funding model platforms

github: # - do not have any, but looking for one.
patreon: # 
custom: # Just looking for an opportunity to grow, learn more and earn. I need to focus my time in web3. Please support my journey in becoming a blockchain guru. 
My name is Simon, just a father , husband and tech geek , looking for a chance to level up my life. 
